---
language: ruby
rvm:
  - 2.0
  - 2.1.5

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt python-pycurl git python-pip ruby ruby-dev build-essential autoconf
  - gem install bundler -v 1.11.2
  # Get ansible install
  - python --version
  - ruby --version

install:
  - bash test/ansible-setup.sh
  - bundle install
  - gem build kitchen-ansiblepush.gemspec
  - bundle install

script:
    - ansible --version
    - export TRAVIS=True
    - run-tests.sh
after_success:
    - echo "Success"